name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build-release
      run: make build-release-nowarn-u -b
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/jcb.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows-latest:
    runs-on: windows-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build-release
      run: make build-release-nowarn-w -b
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/jcb.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 
