name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build-release
      run: make build-release-nowarn-u -b
  windows-latest:
    runs-on: windows-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build-release
      run: make build-release-nowarn-w -b
